language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
    - git init && heroku git:remote -a mydiaryprojectapi
script:
  - heroku run npm test --app mydiaryprojectapi