language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - git remote add heroku https://git.heroku.com/mydiaryprojectapi.git && heroku run npm test --app mydiaryprojectapi