POST https://mydiaryprojectapi.herokuapp.com/api/v1/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "client@mail.com",
  "password": "12345"
}

###

POST https://mydiaryprojectapi.herokuapp.com/api/v1/entries HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0aW5nMkBtYWlsLmNvbSIsImlhdCI6MTYwNDQyNTYyNSwiZXhwIjoxNjA0NDI5MjI1fQ.-ol_AMBwpnubQSNgrnQk8fQ4SX74EWvBhKtniQPHoTQ

{
  "content": "Entry by Client0"
}

###

POST https://mydiaryprojectapi.herokuapp.com/api/v1/entries HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0aW5nQG1haWwuY29tIiwiaWF0IjoxNjA0NDI1NTE5LCJleHAiOjE2MDQ0MjkxMTl9.y3EYCPDvXCQgdIlkjvWbIwOWrwn4NOJtmF3fIjsBIjU

{
  "content": "Entry by Client0"
}

###

GET https://mydiaryprojectapi.herokuapp.com/api/v1/entries HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0aW5nMkBtYWlsLmNvbSIsImlhdCI6MTYwNDQyNTYyNSwiZXhwIjoxNjA0NDI5MjI1fQ.-ol_AMBwpnubQSNgrnQk8fQ4SX74EWvBhKtniQPHoTQ

###

GET http://localhost:3000/api/v1/entries/5f9976895fd3b00640ad04ea HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjkyODQ0MmZlZDQ1ZjMyMTRhZjY0MjMiLCJpYXQiOjE2MDM4OTI0MDMsImV4cCI6MTYwMzg5NjAwM30.sdXr1GUX5lyJf1C8c3qIZyjEv3zzj4ok0yBvuMs_-A0

###

DELETE http://localhost:3000/api/v1/entries/5f9976895fd3b00640ad04ea HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjkyODQ0MmZlZDQ1ZjMyMTRhZjY0MjMiLCJpYXQiOjE2MDM4OTI0MDMsImV4cCI6MTYwMzg5NjAwM30.sdXr1GUX5lyJf1C8c3qIZyjEv3zzj4ok0yBvuMs_-A0