CREATE TABLE IF NOT EXISTS users (
  id bigserial PRIMARY KEY,
  username VARCHAR(225) UNIQUE,
  password_digest VARCHAR(225),
  token VARCHAR(225)
);

INSERT INTO users(email)
  VALUES('testing@mail.com');

CREATE TABLE IF NOT EXISTS entry (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content text NOT NULL
);

INSERT INTO entry(content) 
  VALUES('test diary entry');